import React from 'react';
import type { AdFormat } from './types';
import { BillboardIcon, MagazineIcon, BusStopIcon, NewspaperIcon, SocialMediaIcon, CoffeeShopIcon, SubwayIcon, TechWebsiteIcon, MuralIcon, AirplaneIcon, ProjectionIcon, SoccerIcon, NatureIcon, MovieIcon, HologramIcon, PinterestIcon, FacebookIcon, YouTubeIcon, LinkedInIcon, WeChatChannelsIcon, WeChatOfficialIcon, XiaohongshuIcon, BusWrapIcon, InGameIcon, ArtGalleryIcon, PackagingIcon, InstagramPostIcon, XIcon, TikTokIcon, DouyinIcon, BilibiliIcon, KuaishouIcon } from './components/icons/AdIcons';

export const AD_FORMATS: AdFormat[] = [
  {
    id: 'billboard',
    name: '时代广场广告牌',
    description: "纽约市中心的巨型广告。",
    prompt: "将产品放置在雨夜中霓虹闪烁的时代广场的巨大发光数字广告牌上。场景应具有电影感，湿漉漉的街道上应有倒影。",
    icon: BillboardIcon,
  },
  {
    id: 'magazine',
    name: '奢侈品杂志',
    description: "优雅的整版广告。",
    prompt: "在一本高级时尚杂志的文章旁边，用一整个光面页面创建一个广告。风格应简约、优雅，并配以精致的字体排版。",
    icon: MagazineIcon,
  },
  {
    id: 'bus_stop',
    name: '城市公交站',
    description: "繁华都市的现代广告。",
    prompt: "在白天像伦敦这样繁华的城市里，将产品展示在现代化的玻璃和钢结构公交车站候车亭广告中。背景中应有行人走过。",
    icon: BusStopIcon,
  },
  {
    id: 'newspaper',
    name: '复古报纸',
    description: "经典的复古风格广告。",
    prompt: "在 1950 年代的报纸上设计一则经典的黑白分类广告。产品应以复古风格插图呈现，配以复古字体和颗粒状纹理。",
    icon: NewspaperIcon,
  },
  {
    id: 'social_media',
    name: '社交媒体快拍',
    description: "引人入胜的赞助帖子。",
    prompt: "为一款流行的社交媒体应用创建一个赞助快拍帖子，通过一个人手中的智能手机观看。包括“立即购买”按钮等用户界面元素。",
    icon: SocialMediaIcon,
  },
  {
    id: 'instagram_post',
    name: 'Instagram 帖子',
    description: '高颜值的方形图片帖子。',
    prompt: '在一部智能手机的屏幕上，展示一个 Instagram 方形图片帖子。产品应处于一张精心拍摄、光线优美的照片中。帖子下方应显示用户名、一段引人入胜的描述、相关的标签以及点赞和评论的图标。',
    icon: InstagramPostIcon,
  },
  {
    id: 'tiktok',
    name: 'TikTok 视频',
    description: '病毒式传播的竖屏短视频。',
    prompt: '为 TikTok “为你推荐”页面创建一个竖屏短视频的截图。产品应作为视频内容的核心，背景可以是热门挑战或教程。界面应包括用户名、标题、热门音轨名称以及点赞、评论和分享按钮。',
    icon: TikTokIcon,
  },
  {
    id: 'x_post',
    name: 'X (推特) 帖子',
    description: '简洁明了的推文卡片。',
    prompt: '创建一个 X (前身为推特) 的推文截图。产品图片应清晰地显示在推文卡片中，上方是用户的头像、名称、ID 和一段简短的宣传文案。下方应显示回复、转发和点赞的数量。',
    icon: XIcon,
  },
  {
    id: 'pinterest',
    name: 'Pinterest 帖子',
    description: '展示生活方式的灵感图。',
    prompt: '设计一个富有灵感的竖版 Pinterest 图钉。产品应出现在一张风格优美、充满美学的生活方式照片中，并配有吸引人的标题文字叠加。',
    icon: PinterestIcon,
  },
  {
    id: 'facebook_cover',
    name: 'Facebook 封面',
    description: '为您的品牌主页增添风采。',
    prompt: '创建一张以产品为特色的宽幅 Facebook 封面照片。场景应充满活力、引人注目，一侧留有放置头像的空间。设计应看起来专业且吸引人。',
    icon: FacebookIcon,
  },
  {
    id: 'youtube_banner',
    name: 'YouTube 频道头图',
    description: '吸引订阅者的频道艺术。',
    prompt: '生成一张 YouTube 频道头图 (2560x1440像素)，以产品为中心。主要元素和产品应集中在中央的“安全区域”(1546x423像素) 内，以确保在所有设备上都能看清。背景应有主题性且高质量。',
    icon: YouTubeIcon,
  },
  {
    id: 'linkedin_banner',
    name: '领英个人/公司横幅',
    description: '专业的品牌形象展示。',
    prompt: '为公司或个人品牌资料设计一个专业的领英横幅。产品应优雅地展示在干净、现代、专业的背景前。整体基调应精致且值得信赖。',
    icon: LinkedInIcon,
  },
  {
    id: 'douyin',
    name: '抖音视频',
    description: '国内热门的短视频广告。',
    prompt: '模拟一个在抖音APP“推荐”页上滑到的竖屏短视频截图。产品应是视频的主角，场景可以是流行的剧情、开箱或评测。手机界面上要能看到创作者的头像、昵称、视频文案、背景音乐，以及右侧的点赞、评论、转发图标。',
    icon: DouyinIcon,
  },
  {
    id: 'wechat_channels',
    name: '微信视频号封面',
    description: '吸引眼球的竖版短视频封面。',
    prompt: '为微信视频号短视频创建一个竖版封面图 (宽高比3:4)。产品应是明确的焦点，具有引人注目的视觉效果和能鼓励观众点击观看的风格。背景应充满动感或具有美感。',
    icon: WeChatChannelsIcon,
  },
  {
    id: 'wechat_official',
    name: '微信公众号头图',
    description: '文章的专业横版主图。',
    prompt: '为微信公众号文章生成一张横版主图 (宽高比2.35:1)。产品应被清晰、有吸引力地展示。整体图片应高质量，并适合作为专题文章的头图。',
    icon: WeChatOfficialIcon,
  },
  {
    id: 'xiaohongshu',
    name: '小红书帖子封面',
    description: '高颜值的种草笔记封面。',
    prompt: '为小红书帖子设计一张视觉吸引力强的竖版封面图 (宽高比3:4)。场景应具有美感和生活方式导向，在真实而理想的环境中展示产品。风格应干净、明亮、高质量，能激发用户“收藏”该帖子。',
    icon: XiaohongshuIcon,
  },
  {
    id: 'bilibili_cover',
    name: 'B站视频封面',
    description: '吸引点击的横版视频封面。',
    prompt: '为Bilibili (B站) 视频设计一张高吸引力的横版封面图 (16:9)。产品应以夸张或有趣的方式展示，封面可以包含醒目的标题文字和有趣的贴图元素，以最大化点击率。整体风格要符合B站年轻、二次元的社区氛围。',
    icon: BilibiliIcon,
  },
  {
    id: 'kuaishou_video',
    name: '快手短视频',
    description: '充满生活气息的短视频。',
    prompt: '生成一张快手风格的竖屏短视频截图。场景应更贴近日常生活，真实而接地气，例如在一个家庭场景或户外活动中展示产品。界面上应有用户头像、标题以及标志性的“双击666”风格的点赞互动元素。',
    icon: KuaishouIcon,
  },
  {
    id: 'coffee_shop',
    name: '咖啡店海报',
    description: "舒适、有艺术感的海报。",
    prompt: "将产品展示在一张带框的海报上，海报挂在一家舒适、质朴的咖啡店的裸砖墙上，灯光温暖而有氛围。前景的桌子上可以放着一杯热气腾腾的咖啡。",
    icon: CoffeeShopIcon,
  },
  {
    id: 'subway',
    name: '地铁车厢广告',
    description: "面向日常通勤者的广告。",
    prompt: "将包含产品的广告放置在拥挤、明亮的地铁车厢的弧形内壁上，地点可能在东京或纽约。",
    icon: SubwayIcon,
  },
  {
    id: 'tech_website',
    name: '科技网站特写',
    description: "产品发布日的特色卡片。",
    prompt: "在一个热门的科技产品发布网站上，将产品作为特色项目展示。图片应看起来像一张截图，并能看到点赞数和评论等用户界面元素。",
    icon: TechWebsiteIcon,
  },
  {
    id: 'mural',
    name: '建筑墙绘',
    description: "巨大的手绘壁画。",
    prompt: "将产品变成一幅巨大的、手绘的、照片般逼真的壁画，画在像布鲁克林这样的艺术城市街区的砖砌建筑侧面。",
    icon: MuralIcon,
  },
  {
    id: 'airplane',
    name: '机上杂志',
    description: "为环球旅行者设计的广告。",
    prompt: "为产品在机上杂志的一页上创建一个广告，杂志放在飞机小桌板上，旁边有护照和饮料，窗外是云层。",
    icon: AirplaneIcon,
  },
  {
    id: 'projection',
    name: '建筑投影',
    description: '历史建筑上的灯光秀。',
    prompt: '夜晚，将产品的广告投影到一座宏伟的历史建筑外墙上。投影应充满活力，并能贴合建筑的细节。',
    icon: ProjectionIcon,
  },
  {
    id: 'soccer_stadium',
    name: '足球场边广告',
    description: '比赛期间的滚动横幅。',
    prompt: '在一场夜间比赛中，将产品展示在座无虚席的足球场边线的滚动 LED 横幅上。背景中应能看到观众和体育场的灯光。',
    icon: SoccerIcon,
  },
  {
    id: 'nature',
    name: '自然路标',
    description: '宁静森林中的木制标牌。',
    prompt: '在一个宁静、阳光斑驳的森林里，将产品展示在一个质朴的木制路标上。光线应自然柔和，景深要浅。',
    icon: NatureIcon,
  },
  {
    id: 'movie_scene',
    name: '电影场景植入',
    description: '电影中的微妙产品植入。',
    prompt: '在一个富有戏剧性和电影感的场景中，将产品巧妙地放在桌子上。灯光应具有情绪化和氛围感，仿佛来自一部新黑色电影。',
    icon: MovieIcon,
  },
  {
    id: 'hologram',
    name: '未来全息广告',
    description: '赛博朋克城市中的广告。',
    prompt: '在一个未来主义的赛博朋克城市夜景中，创建一个产品的悬浮全息广告，背景要有飞行汽车和霓虹灯。',
    icon: HologramIcon,
  },
  {
    id: 'bus_wrap',
    name: '公交车身广告',
    description: '城市街道上移动的广告牌。',
    prompt: '将产品作为一幅大型、高分辨率的广告，包裹在一辆现代城市公交车的侧面，公交车正行驶在阳光明媚、繁华的城市街道上。广告应充满活力、引人注目。',
    icon: BusWrapIcon,
  },
  {
    id: 'in_game',
    name: '游戏内广告牌',
    description: '在虚拟世界中投放广告。',
    prompt: '将产品放置在一个未来感十足、充满动作的视频游戏场景中的发光数字广告牌上。环境应细节丰富，有霓虹灯和高科技的动感。',
    icon: InGameIcon,
  },
  {
    id: 'art_gallery',
    name: '艺术画廊展品',
    description: '将产品作为艺术品展出。',
    prompt: '在一个极简主义的现代艺术画廊中，将产品作为中心展品。它可以放在聚光灯下的基座上，或者作为一幅巨大的裱框作品挂在干净的白墙上。氛围应精致而宁静。',
    icon: ArtGalleryIcon,
  },
  {
    id: 'packaging',
    name: '产品包装',
    description: '产品零售包装的模型。',
    prompt: '创建一个逼真的产品包装模型 (例如盒子、袋子或瓶子) 来展示产品。包装应设计精良，放置在干净、中性的表面上，并有专业的摄影棚灯光。',
    icon: PackagingIcon,
  }
];